version: '3.7'

services:

  web:
    container_name: ralphsplace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
